#12 Add sort by monotonicity
mgedmin/dozer pull request #13
Opened 2020-11-12 10:02 UTC by wylswz

2020-11-12 17:07 UTC, mgedmin requested changes
The sort regression needs to be fixed, the rest is less important.

Hmm, where's my Travis CI build status?

2020-11-12 17:07 UTC, mgedmin commented on dozer/util.py
> +    return sorted(d.items(), key=lambda x: sort_key(x[1]), reverse=reversed)
Minor: this file is missing a trailing newline.

2020-11-12 17:07 UTC, mgedmin commented on dozer/util.py
> +    return inc_cnt / (inc_cnt + dec_cnt)
This seems expensive.  Surely we could compute inc_cnt and dec_cnt by doing one loop through objs?  Something line this ought to work:

```python
inc_cnt = 0
dec_cnt = 1
for i in range(len(objs) - 1):
    if objs[i+1] > objs[i]:
        inc_cnt += 1
    else:
        dec_cnt += 1
```

2020-11-12 17:09 UTC, mgedmin commented
Thank you for your contribution!  It looks very interesting indeed.

2020-11-13 02:33 UTC, wylswz commented
conversations resolved

2020-11-13 02:37 UTC, wylswz commented on dozer/media/graphs.html
> +                </select>
Use "none" as default

2020-11-13 04:10 UTC, wylswz commented on dozer/media/graphs.html
> +                </select>
The display is inconsistent with actual parameter. Pass the selection back to front end and set option attribute

2020-11-13 07:23 UTC, mgedmin approved these changes
LGTM!

2020-11-13 07:23 UTC, merged

2020-11-13 07:23 UTC, mgedmin commented
Thank you!